/** Capital de cada departamento — único dato adicional mostrado en el mapa (hecho verificable, sin cifras de negocio inventadas). */
export const departmentCapitals: Record<string, string> = {
  Amazonas: "Leticia",
  Antioquia: "Medellín",
  Arauca: "Arauca",
  Atlántico: "Barranquilla",
  "Bogotá D.C.": "Bogotá",
  Bolívar: "Cartagena de Indias",
  Boyacá: "Tunja",
  Caldas: "Manizales",
  Caquetá: "Florencia",
  Casanare: "Yopal",
  Cauca: "Popayán",
  Cesar: "Valledupar",
  Chocó: "Quibdó",
  Córdoba: "Montería",
  Cundinamarca: "Bogotá",
  Guainía: "Inírida",
  Guaviare: "San José del Guaviare",
  Huila: "Neiva",
  "La Guajira": "Riohacha",
  Magdalena: "Santa Marta",
  Meta: "Villavicencio",
  Nariño: "Pasto",
  "Norte de Santander": "Cúcuta",
  Putumayo: "Mocoa",
  Quindío: "Armenia",
  Risaralda: "Pereira",
  Santander: "Bucaramanga",
  Sucre: "Sincelejo",
  Tolima: "Ibagué",
  "Valle del Cauca": "Cali",
  Vaupés: "Mitú",
  Vichada: "Puerto Carreño",
  "San Andrés y Providencia": "San Andrés",
};
