/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as ProcesoRouteImport } from './routes/proceso'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosCompraDeSentenciasRouteImport } from './routes/servicios.compra-de-sentencias'
import { Route as ServiciosFactoringRouteImport } from './routes/servicios.factoring'
import { Route as ServiciosInversionRouteImport } from './routes/servicios.inversion'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesoRoute = ProcesoRouteImport.update({
  id: '/proceso',
  path: '/proceso',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosCompraDeSentenciasRoute =
  ServiciosCompraDeSentenciasRouteImport.update({
    id: '/compra-de-sentencias',
    path: '/compra-de-sentencias',
    getParentRoute: () => ServiciosRoute,
  } as any)
const ServiciosFactoringRoute = ServiciosFactoringRouteImport.update({
  id: '/factoring',
  path: '/factoring',
  getParentRoute: () => ServiciosRoute,
} as any)
const ServiciosInversionRoute = ServiciosInversionRouteImport.update({
  id: '/inversion',
  path: '/inversion',
  getParentRoute: () => ServiciosRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/proceso': typeof ProcesoRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicios/compra-de-sentencias': typeof ServiciosCompraDeSentenciasRoute
  '/servicios/factoring': typeof ServiciosFactoringRoute
  '/servicios/inversion': typeof ServiciosInversionRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/proceso': typeof ProcesoRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicios/compra-de-sentencias': typeof ServiciosCompraDeSentenciasRoute
  '/servicios/factoring': typeof ServiciosFactoringRoute
  '/servicios/inversion': typeof ServiciosInversionRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/servicios': typeof ServiciosIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/proceso': typeof ProcesoRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicios/compra-de-sentencias': typeof ServiciosCompraDeSentenciasRoute
  '/servicios/factoring': typeof ServiciosFactoringRoute
  '/servicios/inversion': typeof ServiciosInversionRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacto'
    | '/nosotros'
    | '/politica-de-privacidad'
    | '/proceso'
    | '/servicios'
    | '/terminos-y-condiciones'
    | '/admin/login'
    | '/blog/$slug'
    | '/servicios/compra-de-sentencias'
    | '/servicios/factoring'
    | '/servicios/inversion'
    | '/admin/'
    | '/blog/'
    | '/servicios/'
    | '/admin/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/politica-de-privacidad'
    | '/proceso'
    | '/terminos-y-condiciones'
    | '/admin/login'
    | '/blog/$slug'
    | '/servicios/compra-de-sentencias'
    | '/servicios/factoring'
    | '/servicios/inversion'
    | '/admin'
    | '/blog'
    | '/servicios'
    | '/admin/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacto'
    | '/nosotros'
    | '/politica-de-privacidad'
    | '/proceso'
    | '/servicios'
    | '/terminos-y-condiciones'
    | '/admin/login'
    | '/blog/$slug'
    | '/servicios/compra-de-sentencias'
    | '/servicios/factoring'
    | '/servicios/inversion'
    | '/admin/'
    | '/blog/'
    | '/servicios/'
    | '/admin/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  ProcesoRoute: typeof ProcesoRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proceso': {
      id: '/proceso'
      path: '/proceso'
      fullPath: '/proceso'
      preLoaderRoute: typeof ProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/compra-de-sentencias': {
      id: '/servicios/compra-de-sentencias'
      path: '/compra-de-sentencias'
      fullPath: '/servicios/compra-de-sentencias'
      preLoaderRoute: typeof ServiciosCompraDeSentenciasRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/factoring': {
      id: '/servicios/factoring'
      path: '/factoring'
      fullPath: '/servicios/factoring'
      preLoaderRoute: typeof ServiciosFactoringRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/servicios/inversion': {
      id: '/servicios/inversion'
      path: '/inversion'
      fullPath: '/servicios/inversion'
      preLoaderRoute: typeof ServiciosInversionRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServiciosRouteChildren {
  ServiciosCompraDeSentenciasRoute: typeof ServiciosCompraDeSentenciasRoute
  ServiciosFactoringRoute: typeof ServiciosFactoringRoute
  ServiciosInversionRoute: typeof ServiciosInversionRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosCompraDeSentenciasRoute: ServiciosCompraDeSentenciasRoute,
  ServiciosFactoringRoute: ServiciosFactoringRoute,
  ServiciosInversionRoute: ServiciosInversionRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  ProcesoRoute: ProcesoRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
